/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author s.lucas
 */
public class FrSobre extends javax.swing.JDialog {

    /**
     * Creates new form FrSobre
     */
    public FrSobre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTexto = new javax.swing.JLabel();
        iconePrincipal = new javax.swing.JLabel();
        lblVersao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDesenvolvedor = new javax.swing.JLabel();
        lblGitHub2 = new javax.swing.JLabel();
        lblGitHub = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(244, 255, 212));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTexto.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        lblTexto.setText("SOBRE");
        jPanel2.add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 11, -1, -1));

        iconePrincipal.setForeground(new java.awt.Color(102, 0, 51));
        iconePrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/poke128px.png"))); // NOI18N
        jPanel2.add(iconePrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 58, -1, -1));

        lblVersao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblVersao.setText("Versão 1.0");
        jPanel2.add(lblVersao, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 192, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("23/09/2024");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 217, -1, -1));

        lblDesenvolvedor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblDesenvolvedor.setText("Desenvolvido por: Jean Pereira Zeni e Henrique Fantinel");
        jPanel2.add(lblDesenvolvedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 251, -1, 28));

        lblGitHub2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/github32px.png"))); // NOI18N
        lblGitHub2.setText("GitHub: Henrique");
        lblGitHub2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGitHub2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGitHub2MouseClicked(evt);
            }
        });
        jPanel2.add(lblGitHub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, 30));

        lblGitHub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/github32px.png"))); // NOI18N
        lblGitHub.setText("GitHub: Jean");
        lblGitHub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGitHub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGitHubMouseClicked(evt);
            }
        });
        jPanel2.add(lblGitHub, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGitHub2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGitHub2MouseClicked
        try {
            Desktop desktop = Desktop.getDesktop();
            URI uri = new URI("https://github.com/hfantinel");
            desktop.browse(uri);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lblGitHub2MouseClicked

    private void lblGitHubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGitHubMouseClicked
        try {
            Desktop desktop = Desktop.getDesktop();
            URI uri = new URI("https://github.com/Jean-Zeni");
            desktop.browse(uri);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lblGitHubMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrSobre dialog = new FrSobre(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconePrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDesenvolvedor;
    private javax.swing.JLabel lblGitHub;
    private javax.swing.JLabel lblGitHub2;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblVersao;
    // End of variables declaration//GEN-END:variables
}
